name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Prepare Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 18

      - name: NPM Install
        run: npm ci

      - name: NPM Lint
        run: npm run lint
